[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/src=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/",
]

[invariant]
runs = 64
depth = 64
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
